### ISSUE TITLE
Deep Links

### ISSUE THREAD

**Issue by radius314** [jbraswell/do-i-have-the-bmlt#1]
As a consumer of the doihavethebmlt.org application, I would like to be able to share with someone a link with a given search result.

**Comment by jbraswell** [comment]
Can you explain the desired user experience?

**Comment by radius314** [comment]
1) Look up something
2) Click share
3) you get a link that you can copy
4) someone clicks that link and then they back the same lookup.

**Comment by jbraswell** [comment]
done

**Comment by radius314** [comment]
was something new deployed?

**Comment by jbraswell** [comment]
Yes. You may need to clear your caches. There's a new button.

**Comment by radius314** [comment]
is this on cloudfront?

**Comment by jbraswell** [comment]
Yes. Caches on CF have been invalidated.

**Comment by radius314** [comment]
I'm seeing it now.  Is it not taking your current location anymore?  It still seems to be asking, but then prompting with the modal for a location.

**Comment by jbraswell** [comment]
It still tries to get your current location. If it fails (for whatever reason), it falls back to asking.

**Comment by jbraswell** [comment]
https://github.com/jbraswell/do-i-have-the-bmlt/blob/master/src/LocationBox.js#L45

Also if it can't determine your location in 15s, it'll prompt. The getCurrentPosition method is kind of flaky - lots of complaints about it throughout the Internet.
